language: node_js
node_js:
- 8
install:
- npm install
script:
- npm test
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: Ono3X5ytTAEJvYUug5FbmwYOz0spF0MWw5L/S8nIZvKWtpg7CYXOdBdIO322yd9bppbQ99FdOQ4HK4Yh4RaCCK3A323hQV+Q8u7O8nZMglipHk7AyzWYRO/Xx6ziEDQ4RT7xATN+QlCVF/ZSLJduhWUQBchi/tBrt9rQrSTUQ4mJOV537B4igRqWCbFXU+Z+6kM4tv4YwEcVploCjj2RQtg8w1oo2EWzrFAg3l82k+TGSYTuAHlu9JsxrZHQhgwEsrYJ4/87lRV7klv/sRzxy3LOC4Hv+VvHamZ4oLIj7KvD2Ed+lsBAmIc19GSZatzdXxhFAHg0AZ5Ni1ciZQaYve5FV+TDq3wAOkufBpMXF4+gJheJYRAFq8OmC6Eg9NUxeNCiGgeERgW8Vrw3Iueo2ZZ+3tv6WikCEZi6+ZYcFgbbKZS3jwH+AvbXh+i/Oo8a6BwPmmxpV6M3Y6VUH0rWif3xm7+4F1qpjNVfsA0/DgTyLHda3N6YOLVbFPRneynsLwsHWeBM0kRJT09HFglE18SnOlHVLFQY+l9kWXsJkO2zuUd190L3GmTPCcddqQgnk57/3T5AFF4ZQ3D5fyckHULf+tUqff9Q2GmIPXXtvNGciEP+wVbHF/4PjmZZmNQ46PjRvsfP5sa7ADXYSCHEZP+BPa1/rgSmm+HVSrLqSLk=
  project: portfolio-3a79e
  on:
    branch: master
  mapbox_access_token:
    secure: cIIQkhLt8rFWTAJhvuZLejH3lJ0LAnhzodqv7fTFAj5YlqdaP7Hgb7nfcriRRTHaiLSnjzZ4A1d7C1lcbdVSmYcP1Kpy5N9V72jm4iMvjuvJbgYP391xoRe2bUZztNmccKCXQYov6CKjtQ4IQpXGFiCaybmJipg915Ct7Apm7CfzEsATsBDM+uW9Wn82vAmYxHkgZvaJPmLytmieGClkbdn9bjxgkujdcod5d/GK9YM5F1A+vSFqD1IlWy3FYiqEtPyjB+hKw5lYmHHfDDh+mwTadBMxh7NT5myeG+AAI+bnB0DVJ6PTKMQipnIfUFCWGH7eE/hV5xA2fZrCJop8jZEPW30zA67JrUw3yrVI+kLSX38eKX8NeDH+o86I+kRGF8TAy1nkwwmJ4lXJUoiFsECKgA7XZqs4FKqwqZuBwFrSf+7Kt40I6nXGAdmNvle3VPMigwQX0NISYx+IEqGXsjrRKfc4N08SGCkC+pOd4TlInwTIcjXonXcBZfz3WNZARXk1o9zDslk1Bk4gHvhPKtUwFygFG9H+lsuMeNzECuOMtnGQ8lsxD+iIZk724KMADhKi90MbWWsIjAdpUGi7bU31oO2seKcnJpihHoXtxYRx3YuD0FmEpf7Sx9UQUoUmt2xoRaoshpfgEODyrGMmi7zLl2shIzWvzuH+5pwAHb0=
  CYCLE_IDENTIFIER:
    secure: Xv1L+j7UQRoL/q4X546m+ZjwJxJShKNOdMfVTS6aeIjm5LEMTYKnyrNeAf+Zy7xfbqRCBJiIUdjCc8dvLLcFl/WdPSir8DRKD+iQkp/eCE3WVJqgyMMUc2DzhbxkRhZXT8/QJWPQfuGXeJu6ioz02U7gIHqfgPNT7DPHLAlnoG1InDjJYswSk6IOU0p21L75Ode4J5fVNmTZsbT5c3t/yKqhUuJ/cpkfaIZQ8DUfGTUgypEg3eBMMr9oDkhwy/4e3GuVnH00OWRnWTbyIjGEw8QHhe3HnReIPT+K+mC2pYlp5+DkhjQBSAR0xRnrZ8yBh0H+yLWGSjIdM8o7XlhniCe7vcW7Ck/vnGbziAL2Bgi6xf1h611lOXqUiIWbl6NGLqlo9tJhcnI5zcR7rW7QLbAFOTYnsq7OwGJXoBQ+JsRvSk9BW6qokuaVBY/ERv4rnaWWlm+EASLHa8uRpmM9VsLch0y0gxt4YxLlwEAr/o2tBWAr8qw76SxnuNYzvUvJ6fYg2A/cjRglHVT/AtNmsl63UhDaeX/FydS3ZwOaHWGGgNTx11+WHBMCtdjLmOgVy1i+TZoawUidcC73s7Zby99xZyYApXnr6FyIzxcdPfgTkWqchpD+fqfjVQYQLsZaCAZvUQh7SGlF0ZSRhUccdjegCkUX+QPtqlQy+HGmxdM=
