language: node_js

node_js:
  - 8

install:
  - npm install

before_script:
  - git checkout package-lock.json

script:
  - npm test
  - npm run build

deploy:
  provider: firebase
  token:
    secure: "jKTijF3HN9n2tfXqshQYPUrQv1kZHV4r7uMb/5rl6Oi00uB0n34dgSCG8o5ILYcD9yGMcSoY8XVrrtwtveuwOafMvV49ZkKu3PlEge6KCEl5cANvpo5QQ5N3aH8N0uv0b0SP9o76gW/MpXnIArVsPsearF9oeHxLzTmOT60VmlHipTZ5FJJaoC46Kl0BUHv5ZnwzoNTpDobFdENaZiCByWppYd1Q6UAg0g2UCFDKPuszPpXRzK1FROQJnUeeDbf8x3PSFMNIJRI1ElJYmE8ipdLKkwY8G6tU+lK5ncsKhU1ZQYShc8p0BwNUR4HCDFVHOS7MuzeRN/cpK4ATF3Q/EmG+dfuXE0kGodJQ8SoPXCuINmpw1Lm0rwNXjHnKUiBmoFaMEqTFvry4mXuiLb75pcCrOsJU4eyuVCaFydba0rLjBudkOMhrR12jIYXmkdKw6uvJ06+9o+yrNTDSFF0ZI+ZYk9cl8X0cRjB1PmygeadsfaG9ADFek6UfQj9aeOIVAmAHyRfKv+OKv6yzlfXHCxE1DlS63HBdwO5VlFXDRmwmo6P+VHq2zosbb4xtrS7qO3fdGHAYnHL1n/AHVWhRyKexv/r7soedLIZxQdrvZWeDRa2BvXZqoumBRqes3zwMSdAiRv6XWcvl/t2sDxOvPlb2lr/wVEu+FuRhxr/fwDs="
  project: "portfolio-3a79e"
