language: node_js

node_js:
  - 8

install:
  - npm install

before_script:
  - git checkout package-lock.json

script:
  - npm test
  - npm run build

deploy:
  provider: firebase
  token:
    secure: "Ono3X5ytTAEJvYUug5FbmwYOz0spF0MWw5L/S8nIZvKWtpg7CYXOdBdIO322yd9bppbQ99FdOQ4HK4Yh4RaCCK3A323hQV+Q8u7O8nZMglipHk7AyzWYRO/Xx6ziEDQ4RT7xATN+QlCVF/ZSLJduhWUQBchi/tBrt9rQrSTUQ4mJOV537B4igRqWCbFXU+Z+6kM4tv4YwEcVploCjj2RQtg8w1oo2EWzrFAg3l82k+TGSYTuAHlu9JsxrZHQhgwEsrYJ4/87lRV7klv/sRzxy3LOC4Hv+VvHamZ4oLIj7KvD2Ed+lsBAmIc19GSZatzdXxhFAHg0AZ5Ni1ciZQaYve5FV+TDq3wAOkufBpMXF4+gJheJYRAFq8OmC6Eg9NUxeNCiGgeERgW8Vrw3Iueo2ZZ+3tv6WikCEZi6+ZYcFgbbKZS3jwH+AvbXh+i/Oo8a6BwPmmxpV6M3Y6VUH0rWif3xm7+4F1qpjNVfsA0/DgTyLHda3N6YOLVbFPRneynsLwsHWeBM0kRJT09HFglE18SnOlHVLFQY+l9kWXsJkO2zuUd190L3GmTPCcddqQgnk57/3T5AFF4ZQ3D5fyckHULf+tUqff9Q2GmIPXXtvNGciEP+wVbHF/4PjmZZmNQ46PjRvsfP5sa7ADXYSCHEZP+BPa1/rgSmm+HVSrLqSLk="
  project: "portfolio-3a79e"
  on:
    branch: master
