# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Super-Linter
      uses: github/super-linter@v2.0.0
    - name: Install Packages
      run: npm ci
    - name: Run Tests
      run: npm test
    - name: Build Page
      run: npm run build
      env:
          REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
          REACT_APP_CYCLE_IDENTIFIER: ${{ secrets.REACT_APP_CYCLE_IDENTIFIER }}
          REACT_APP_TRACKING_CODE: ${{ secrets.REACT_APP_TRACKING_CODE }}
    - name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build
        on: push
